In [1]:
print ('hello world')

hello world


In [6]:
import numpy
numbers = numpy.array([1,2,3,4])
print (numbers)
numbers.dtype

[1 2 3 4]


dtype('int32')

In [15]:
import numpy
dim2 = numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print (dim2[1,1])  
print (dim2[2,:])   # :切片， 行
print (dim2[:,2])   #列

6
[ 9 10 11 12]
[ 3  7 11]


In [21]:
import numpy
vector = numpy.array([0,1,2,3])
vector == 3    #判断， 返回的是一个数组， dtype为bool
eq = (vector == 3 )
print (eq)
print (vector[eq])


[False False False  True]
[3]


In [22]:
import numpy
vector = numpy.array([0,1,2,3])
eq = (vector == 1 )&(vector == 3 ) # 且操作
print (eq)

[False False False False]


In [23]:
import numpy
vector = numpy.array([0,1,2,3])
eq = (vector == 1 )|(vector == 3 )   # 或操作
print (eq)

[False  True False  True]


In [24]:
import numpy
vector = numpy.array([0,1,2,3])
vector = vector.astype(float)        # 类型转换
print (vector)

[0. 1. 2. 3.]


In [26]:
import numpy
dim2 = numpy.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])
dim2.sum(axis=1)                     #按行求和
dim2.sum(axis=0)                     #按列求和

array([15, 18, 21, 24])

In [29]:
import numpy as np                  #别名
np.arange(15).reshape(3,5)          #一维分割

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
import numpy as np                  #别名
np.zeros((3,5))                     #初始化矩阵
np.ones((3,5))                      #初始化矩阵

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
import numpy as np 
np.random.random((2,3))             #随机值

array([[0.75070324, 0.3481429 , 0.75535151],
       [0.12811587, 0.9902591 , 0.27744937]])

In [35]:
import numpy as np 
np.linspace(0,10,3)               #区间中取值

array([ 0.,  5., 10.])

In [36]:
import numpy as np 
dima = np.array([10,20,30,40])
dimb = np.array([1,2,3,4])        
print (dima-dimb)

[ 9 18 27 36]


In [37]:
import numpy as np 
dima = np.array([10,20,30,40])
dimb = np.array([1,2,3,4])        
print (dima+dimb)

[11 22 33 44]


In [38]:
import numpy as np 
dima = np.array([10,20,30,40])
dimb = np.array([1,2,3,4])        
print (dima*dimb)                   #  *乘

[ 10  40  90 160]


In [39]:
import numpy as np 
dima = np.array([10,20,30,40])
dimb = np.array([1,2,3,4])        
print (dima.dot(dimb))              #  卷积

300


In [52]:
import numpy as np 
a = np.floor(10*np.random.random((2,4)))
print (a )
print('----------')
print (a.ravel())                   #  矩阵的多维变一维
print('----------')
a.shape = (4,-1)                    # 重构造， 4行 *列
print (a)
print('----------')
print (a.T)                         # 转置

[[6. 9. 2. 4.]
 [2. 1. 6. 7.]]
----------
----------
[[6. 9.]
 [2. 4.]
 [2. 1.]
 [6. 7.]]
----------
[[6. 2. 2. 6.]
 [9. 4. 1. 7.]]


In [56]:
import numpy as np 
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print (a)
print (b)
print('----------')
print(np.hstack((a,b)))             # 横向拼接
print(np.vstack((a,b)))             # 纵向拼接

[[8. 0.]
 [6. 0.]]
[[4. 8.]
 [3. 5.]]
----------
[[8. 0. 4. 8.]
 [6. 0. 3. 5.]]
[[8. 0.]
 [6. 0.]
 [4. 8.]
 [3. 5.]]


In [58]:
import numpy as np 
a = np.floor(10*np.random.random((2,12)))
print (a)
print('----------')
print(np.hsplit(a,3))                   # 横向分割

[[6. 3. 3. 8. 9. 5. 6. 4. 6. 4. 2. 9.]
 [9. 4. 5. 2. 8. 2. 7. 2. 2. 7. 6. 4.]]
----------
[array([[6., 3., 3., 8.],
       [9., 4., 5., 2.]]), array([[9., 5., 6., 4.],
       [8., 2., 7., 2.]]), array([[6., 4., 2., 9.],
       [2., 7., 6., 4.]])]


In [60]:
import numpy as np 
a = np.floor(10*np.random.random((2,12)))
print (a)
print('----------')
print(np.hsplit(a,(3,5)))                   # 横向分割

[[7. 1. 6. 9. 6. 3. 3. 4. 0. 2. 0. 6.]
 [1. 9. 1. 0. 4. 7. 3. 9. 8. 9. 6. 2.]]
----------
[array([[7., 1., 6.],
       [1., 9., 1.]]), array([[9., 6.],
       [0., 4.]]), array([[3., 3., 4., 0., 2., 0., 6.],
       [7., 3., 9., 8., 9., 6., 2.]])]


In [64]:
import numpy as np 
a = np.floor(10*np.random.random((2,4)))
print (a)
print ('----------------------')
b = a                                # = 是指向相同的地址(数据组织结构一样)，共用一份数据     
b[1,1]=10
b.shape = 4,2
print (a)
print ('----------------------')
print (b)

[[5. 4. 8. 5.]
 [8. 3. 0. 5.]]
[[ 5.  4.]
 [ 8.  5.]
 [ 8. 10.]
 [ 0.  5.]]
----------------------
[[ 5.  4.]
 [ 8.  5.]
 [ 8. 10.]
 [ 0.  5.]]


In [65]:
import numpy as np 
a = np.floor(10*np.random.random((2,4)))
print (a)
print ('----------------------')
b = a.view()                                # view 是指向不同地址(数据组织结构不一样)，共用一份数据     
b[1,1]=10
b.shape = 4,2
print (a)
print ('----------------------')
print (b)


[[2. 5. 2. 2.]
 [8. 2. 2. 6.]]
[[ 2.  5.  2.  2.]
 [ 8. 10.  2.  6.]]
----------------------
[[ 2.  5.]
 [ 2.  2.]
 [ 8. 10.]
 [ 2.  6.]]


In [66]:
import numpy as np 
a = np.floor(10*np.random.random((2,4)))
print (a)
print ('----------------------')
b = a.copy()                                # copy 是指向不同地址(数据组织结构不一样)，不同的数据     
b[1,1]=10
b.shape = 4,2
print (a)
print ('----------------------')
print (b)

[[7. 1. 8. 1.]
 [0. 5. 8. 3.]]
[[7. 1. 8. 1.]
 [0. 5. 8. 3.]]
----------------------
[[ 7.  1.]
 [ 8.  1.]
 [ 0. 10.]
 [ 8.  3.]]


In [70]:
import numpy as np 
a = np.floor(10*np.random.random((5,4)))
print (a)
print ('----------------------')
ind = a.argmax(axis=0)                      #列的最大值
print (ind)
print ('----------------------')
data_max = a[ind,range(a.shape[1])]
print (range(a.shape[0]))
print (data_max)

[[3. 9. 5. 8.]
 [4. 3. 3. 2.]
 [8. 9. 6. 0.]
 [7. 6. 8. 6.]
 [8. 2. 2. 6.]]
----------------------
[2 0 3 0]
----------------------
range(0, 5)
[8. 9. 8. 8.]


In [72]:
import numpy as np 
a = np.floor(10*np.random.random((5,4)))
print (a)
print ('----------------------')
ind = a.argmax(axis=1)                      #行的最大值
print (ind)
print ('----------------------')
data_max = a[range(a.shape[0]),ind]
print (data_max)

[[0. 8. 7. 0.]
 [9. 5. 8. 4.]
 [5. 6. 5. 8.]
 [7. 5. 0. 0.]
 [8. 5. 5. 0.]]
----------------------
[1 0 3 0 0]
----------------------
[8. 9. 8. 7. 8.]


In [73]:
import numpy as np 
a = np.arange(0,40,10)
print (a)
b = np.tile(a,(3,3))                     #  扩展
print (b)            

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]]


In [77]:
import numpy as np 
a = np.array([[4,3,5],[1,2,1]])
print (a)
print ('---------------')
b = np.sort(a,axis=1)                   # 按行排序
print (b)

a = np.array([4,3,1,2])
j = np.argsort(a)                       # 下标排序
print (j)
print ('---------------')
print (a[j])


[[4 3 5]
 [1 2 1]]
---------------
[[3 4 5]
 [1 1 2]]
[2 3 1 0]
---------------
[1 2 3 4]
